import Head from "next/head";
import { setContext } from "@apollo/client/link/context";

import {
  ApolloClient,
  InMemoryCache,
  createHttpLink,
  gql,
} from "@apollo/client";
import NavBar from "@/components/NavBar/NavBar";
import MyPinnedRepo from "@/components/MyPinnedRepo/MyPinnedRepo";

interface PinnedItem {
  name: string;
  id: string;
  projectsUrl: string;
}

type PinnedItems = PinnedItem[];

export default function Home({ pinnedItems }: { pinnedItems: PinnedItems }) {
  console.log(pinnedItems);
  return (
    <>
      <Head>
        <title>next-graphql-task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar></NavBar>
        <MyPinnedRepo pinnedItems={pinnedItems}></MyPinnedRepo>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const token = "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";
  console.log(token);
  const httpLink = createHttpLink({
    uri: "https://api.github.com/graphql",
  });

  const authLink = setContext((_, { headers }) => {
    return {
      headers: {
        ...headers,
        authorization: `Bearer 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`,
      },
    };
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });
  // const client = ...

  const { data } = await client.query({
    query: gql`
      query Viewer {
        viewer {
          login
          pinnedItems(first: 6) {
            totalCount
            edges {
              node {
                ... on Repository {
                  name
                  id
                  projectsUrl
                }
              }
            }
          }
        }
      }
    `,
  });

  let { viewer } = data;
  console.log(data);

  let pinnedItems = viewer.pinnedItems.edges.map(
    ({ node }: { node: PinnedItem }) => node
  );

  console.log(pinnedItems);

  return {
    props: {
      pinnedItems,
    },
  };
}
